export const colors = {
  defaultFont: "var(--defaultFont)",
  primary: "var(--primary)",
  secondary: "var(--secondary)",
  tertiary: "var(--tertiary)",
  success: "var(--success)",
  warning: "var(--warning)",
  danger: "var(--danger)",
  info: "var(--info)",
  black: "var(--black)",
  grey59: "var(--grey59)",
  grey82: "var(--grey82)",
  grey85: "var(--grey85)",
  grey93: "var(--grey93)",
  grey99: "var(--grey99)",
  white: "var(--white)",
  gradientPink: "var(--gradientPink)",
  gradientGrey: "var(--gradientGrey)",
} as const;
